const ignored = [
    '**/.build/**',
    '**/.git/**',
    '**/.github/**',
    '**/.idea/**',
    '**/.phive/**',
    '**/.vscode/**',
    '**/app/**',
    '**/bootstrap/**',
    '**/config/**',
    '**/database/**',
    '**/e2e/**',
    '**/node_modules/**',
    '**/playwright-report/**',
    '**/public/**',

    '**/resources/js/plugins/**',
    '**/resources/lang/**',
    '**/resources/packages/**',
    '**/resources/sass/**',
    '**/resources/types/**',
    '**/routes/**',
    '**/storage/**',
    '**/tests/**',
    '**/tools/**',
    '**/vendor/**',
];
module.exports = { ignored };